###################################################################################################################################################################################
######################################################################### DATASET SPLITS FOR CUSTOM DATASETS ######################################################################
###################################################################################################################################################################################
custom:
  # - train: 100 
  #   test: 20 
  #   batch_size: 32
  # - train: 1000 
  #   test: 200 
  #   batch_size: 32
  - train: 1600 
    test: 400 
    batch_size: 32
  - train: 1725 
    test: 525 
    batch_size: 32
  - train: 10000 
    test: 1000 
    batch_size: 32
