#####################################################################################################################################################################################
######################################################################### DATASET SPLITS FOR STANDARD DATASETS ######################################################################
#####################################################################################################################################################################################
standard:
  - train: 100 
    test: 20
    batch_size: 32
  - train: 1000 
    test: 200
    batch_size: 32
  - train: 10000 
    test: 1000
    batch_size: 32
  - train: 50000 
    test: 10000
    batch_size: 128
  - train: 60000 
    test: 10000
    batch_size: 128
