#################################################################################################################################################################################################
######################################################################### RUN SETTINGS FOR POSITIONAL DESCRIPTORS DATASETS ######################################################################
#################################################################################################################################################################################################
lrs:
  standard:
    - 0.1
    - 0.01
    - 0.005
    - 0.001
    - 0.0001
epochs:
  standard:
    - 800
    - 800
    - 800
    - 800
    - 800
runs:
  standard:
    - 3
    - 3
    - 3
    - 3
    - 3
