###################################################################################################################################################################################
######################################################################### DATASET SPLITS FOR CUSTOM DATASETS ######################################################################
###################################################################################################################################################################################
custom:
  - train: 1600
    test: 400 
    batch_size: 32
  - train: 1725
    test: 525 
    batch_size: 32
  - train: 3200
    test: 700 
    batch_size: 32
